/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package painel;

/**
 *
 * @author santorinoneto
 */
public class Painel extends javax.swing.JFrame {

    /**
     * Creates new form Painel
     */
    public Painel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        lblPingTester = new javax.swing.JLabel();
        lblSrwd = new javax.swing.JLabel();
        lblSauipe = new javax.swing.JLabel();
        lblTaipu = new javax.swing.JLabel();
        lblSalinas = new javax.swing.JLabel();
        lblZabbix = new javax.swing.JLabel();
        lblJaua = new javax.swing.JLabel();
        lblPajucara = new javax.swing.JLabel();
        lblItacimirim = new javax.swing.JLabel();
        lblBdcentral = new javax.swing.JLabel();
        lblolivenca = new javax.swing.JLabel();
        lblHumaita = new javax.swing.JLabel();
        lblIntranet = new javax.swing.JLabel();
        lblAbrolhos = new javax.swing.JLabel();
        lblTermometroAlmx = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btPing = new javax.swing.JButton();
        txtSrwd = new javax.swing.JTextField();
        txtItacimirim = new javax.swing.JTextField();
        txtSauipe = new javax.swing.JTextField();
        txtBdcentral = new javax.swing.JTextField();
        txtTaipu = new javax.swing.JTextField();
        txtJaua = new javax.swing.JTextField();
        txtHumaita = new javax.swing.JTextField();
        txtPajucara = new javax.swing.JTextField();
        txtAbrolhos = new javax.swing.JTextField();
        txtZabbix = new javax.swing.JTextField();
        txtIntranet = new javax.swing.JTextField();
        txtOlivenca = new javax.swing.JTextField();
        txtSalinas = new javax.swing.JTextField();
        txtTermometroAlmx = new javax.swing.JTextField();
        lblTermometroNTI = new javax.swing.JLabel();
        txtTermometroNTI = new javax.swing.JTextField();
        lblTermometroCPD = new javax.swing.JLabel();
        txtTermometroCPD = new javax.swing.JTextField();
        lblGamboa = new javax.swing.JLabel();
        lvlMonteserrat = new javax.swing.JLabel();
        lblBacula = new javax.swing.JLabel();
        txtGamboa = new javax.swing.JTextField();
        txtMonteserrat = new javax.swing.JTextField();
        txtBacula = new javax.swing.JTextField();
        lblAlcobaca = new javax.swing.JLabel();
        txtAlcobaca = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenuItem4.setText("jMenuItem4");
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("jMenuItem3");
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setVisible(true);

        lblPingTester.setText("Ping Tester by Santorino");

        lblSrwd.setText("Srwd221");

        lblSauipe.setText("Sauipe");

        lblTaipu.setText("Taipu");

        lblSalinas.setText("Salinas");

        lblZabbix.setText("Zabbix");

        lblJaua.setText("Jaua");

        lblPajucara.setText("Pajucara");

        lblItacimirim.setText("Itacimirim");

        lblBdcentral.setText("BD-Central");

        lblolivenca.setText("Olivença");

        lblHumaita.setText("Humaita");

        lblIntranet.setText("Intranet");

        lblAbrolhos.setText("Abrolhos");

        lblTermometroAlmx.setText("Term. Almx");

        btPing.setText("Ping");
        btPing.setMaximumSize(new java.awt.Dimension(63, 23));
        btPing.setMinimumSize(new java.awt.Dimension(63, 23));
        btPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPingActionPerformed(evt);
            }
        });

        txtSrwd.setEditable(false);
        txtSrwd.setToolTipText("");

        txtItacimirim.setEditable(false);

        txtSauipe.setEditable(false);

        txtBdcentral.setEditable(false);

        txtTaipu.setEditable(false);

        txtJaua.setEditable(false);

        txtHumaita.setEditable(false);

        txtPajucara.setEditable(false);
        txtPajucara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPajucaraActionPerformed(evt);
            }
        });

        txtAbrolhos.setEditable(false);
        txtAbrolhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAbrolhosActionPerformed(evt);
            }
        });

        txtZabbix.setEditable(false);

        txtIntranet.setEditable(false);

        txtOlivenca.setEditable(false);

        txtSalinas.setEditable(false);

        txtTermometroAlmx.setEditable(false);

        lblTermometroNTI.setText("Term. NTI");

        txtTermometroNTI.setEditable(false);

        lblTermometroCPD.setText("Term. CPD");

        txtTermometroCPD.setEditable(false);

        lblGamboa.setText("Gamboa");

        lvlMonteserrat.setText("Monteserrat");

        lblBacula.setText("Bacula");

        txtGamboa.setEditable(false);

        txtMonteserrat.setEditable(false);

        txtBacula.setEditable(false);

        lblAlcobaca.setText("Alcobaça");

        txtAlcobaca.setEditable(false);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSrwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSauipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTaipu)
                                    .addComponent(lblJaua)
                                    .addComponent(lblZabbix)
                                    .addComponent(lblolivenca)
                                    .addComponent(lblTermometroAlmx)
                                    .addComponent(lblTermometroCPD)
                                    .addComponent(lblTermometroNTI))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblBacula)
                        .addGap(48, 48, 48)))
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblPingTester)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTermometroCPD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTermometroNTI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTermometroAlmx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOlivenca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtZabbix, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJaua, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTaipu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSauipe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSrwd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBacula))
                        .addGap(46, 46, 46)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGamboa)
                            .addComponent(lblAlcobaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lvlMonteserrat)
                            .addComponent(lblSalinas)
                            .addComponent(lblIntranet)
                            .addComponent(lblAbrolhos)
                            .addComponent(lblPajucara)
                            .addComponent(lblHumaita)
                            .addComponent(lblBdcentral)
                            .addComponent(lblItacimirim))
                        .addGap(37, 37, 37)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGamboa)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIntranet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtAbrolhos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPajucara, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHumaita, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBdcentral, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtItacimirim, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSalinas, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(txtAlcobaca)
                            .addComponent(txtMonteserrat))
                        .addGap(34, 34, 34))))
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btPing, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(lblPingTester)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                                .addComponent(lblGamboa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSalinas))
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addComponent(txtItacimirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBdcentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHumaita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPajucara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAbrolhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIntranet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGamboa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMonteserrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlMonteserrat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAlcobaca)
                            .addComponent(txtAlcobaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSrwd)
                            .addComponent(txtSrwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSauipe)
                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSauipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblBdcentral)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTaipu)
                            .addComponent(txtTaipu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHumaita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJaua)
                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtJaua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPajucara)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblZabbix)
                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtZabbix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAbrolhos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblolivenca, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtOlivenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIntranet)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTermometroAlmx)
                            .addComponent(txtTermometroAlmx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTermometroNTI)
                            .addComponent(txtTermometroNTI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTermometroCPD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTermometroCPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBacula)
                            .addComponent(txtBacula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblItacimirim))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btLimpar)
                    .addComponent(btPing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPingActionPerformed
        Ping p1 = new Ping();
        p1.pingar("10.71.50.2");
        txtSrwd.setText(p1.result);

        Ping p2 = new Ping();
        p2.pingar("10.71.50.25");
        txtSauipe.setText(p2.result);

        Ping p3 = new Ping();
        p3.pingar("10.71.50.3");
        txtGamboa.setText(p3.result);

        Ping p4 = new Ping();
        p4.pingar("10.71.50.23");
        txtIntranet.setText(p4.result);

        Ping p5 = new Ping();
        p5.pingar("10.71.50.6");
        txtAlcobaca.setText(p5.result);

        Ping p6 = new Ping();
        p6.pingar("10.71.50.3");
        txtGamboa.setText(p6.result);

        Ping p7 = new Ping();
        p7.pingar("10.71.50.36");
        txtAbrolhos.setText(p7.result);

        Ping p8 = new Ping();
        p8.pingar("10.71.50.46");
        txtZabbix.setText(p8.result);

        Ping p9 = new Ping();
        p9.pingar("10.71.50.47");
        txtJaua.setText(p9.result);

        Ping p10 = new Ping();
        p10.pingar("10.71.50.60");
        txtBdcentral.setText(p10.result);

        Ping p11 = new Ping();
        p11.pingar("10.71.50.73");
        txtOlivenca.setText(p11.result);

        Ping p12 = new Ping();
        p12.pingar("10.71.50.75");
        txtHumaita.setText(p12.result);

        Ping p13 = new Ping();
        p13.pingar("10.71.50.50");
        txtItacimirim.setText(p13.result);

        Ping p14 = new Ping();
        p14.pingar("10.71.50.64");
        txtTaipu.setText(p14.result);

        Ping p15 = new Ping();
        p15.pingar("10.71.50.64");
        txtTaipu.setText(p15.result);

        Ping p16 = new Ping();
        p16.pingar("10.71.200.8");
        txtMonteserrat.setText(p16.result);

        Ping p17 = new Ping();
        p17.pingar("10.71.50.89");
        txtBacula.setText(p17.result);

        Ping p18 = new Ping();
        p18.pingar("10.71.50.16");
        txtSalinas.setText(p18.result);

        Ping p19 = new Ping();
        p19.pingar("10.71.200.25");
        txtTermometroNTI.setText(p19.result);

        Ping p20 = new Ping();
        p20.pingar("10.71.200.26");
        txtTermometroCPD.setText(p20.result);

        Ping p21 = new Ping();
        p21.pingar("10.71.200.5");
        txtTermometroAlmx.setText(p21.result);

        Ping p22 = new Ping();
        p22.pingar("10.71.50.53");
        txtPajucara.setText(p22.result);
    }//GEN-LAST:event_btPingActionPerformed

    private void txtPajucaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPajucaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPajucaraActionPerformed

    private void txtAbrolhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbrolhosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAbrolhosActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtAbrolhos.setText("");
        txtAlcobaca.setText("");
        txtBacula.setText("");
        txtBdcentral.setText("");
        txtGamboa.setText("");
        txtHumaita.setText("");
        txtIntranet.setText("");
        txtItacimirim.setText("");
        txtJaua.setText("");
        txtMonteserrat.setText("");
        txtOlivenca.setText("");
        txtPajucara.setText("");
        txtSalinas.setText("");
        txtSauipe.setText("");
        txtSrwd.setText("");
        txtTaipu.setText("");
        txtTermometroAlmx.setText("");
        txtTermometroAlmx.setText("");
        txtTermometroCPD.setText("");
        txtTermometroNTI.setText("");
        txtZabbix.setText("");

    }//GEN-LAST:event_btLimparActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    public javax.swing.JButton btPing;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAbrolhos;
    private javax.swing.JLabel lblAlcobaca;
    private javax.swing.JLabel lblBacula;
    private javax.swing.JLabel lblBdcentral;
    private javax.swing.JLabel lblGamboa;
    private javax.swing.JLabel lblHumaita;
    private javax.swing.JLabel lblIntranet;
    private javax.swing.JLabel lblItacimirim;
    private javax.swing.JLabel lblJaua;
    private javax.swing.JLabel lblPajucara;
    private javax.swing.JLabel lblPingTester;
    private javax.swing.JLabel lblSalinas;
    private javax.swing.JLabel lblSauipe;
    private javax.swing.JLabel lblSrwd;
    private javax.swing.JLabel lblTaipu;
    private javax.swing.JLabel lblTermometroAlmx;
    private javax.swing.JLabel lblTermometroCPD;
    private javax.swing.JLabel lblTermometroNTI;
    private javax.swing.JLabel lblZabbix;
    private javax.swing.JLabel lblolivenca;
    private javax.swing.JLabel lvlMonteserrat;
    private javax.swing.JTextField txtAbrolhos;
    private javax.swing.JTextField txtAlcobaca;
    private javax.swing.JTextField txtBacula;
    private javax.swing.JTextField txtBdcentral;
    private javax.swing.JTextField txtGamboa;
    private javax.swing.JTextField txtHumaita;
    private javax.swing.JTextField txtIntranet;
    private javax.swing.JTextField txtItacimirim;
    private javax.swing.JTextField txtJaua;
    private javax.swing.JTextField txtMonteserrat;
    private javax.swing.JTextField txtOlivenca;
    private javax.swing.JTextField txtPajucara;
    private javax.swing.JTextField txtSalinas;
    private javax.swing.JTextField txtSauipe;
    private javax.swing.JTextField txtSrwd;
    private javax.swing.JTextField txtTaipu;
    private javax.swing.JTextField txtTermometroAlmx;
    private javax.swing.JTextField txtTermometroCPD;
    private javax.swing.JTextField txtTermometroNTI;
    private javax.swing.JTextField txtZabbix;
    // End of variables declaration//GEN-END:variables
}
